on:
push:
branches:
- main
pull_request:
branches:
- main

permissions:
contents: read

jobs:
terraform:
name: Terraform
runs-on: ubuntu-latest

env:
AWS_REGION: ap-south-1
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

steps:
- name: Checkout Repository
uses: actions/checkout@v3

- name: Setup Terraform
uses: hashicorp/setup-terraform@v2
with:
terraform_version: 1.9.5

- name: Terraform Init
run: terraform init

- name: Terraform Format Check
run: terraform fmt -check

- name: Terraform Validate
run: terraform validate

- name: Terraform Plan with tfvars
run: terraform plan -input=false -var-file="terraform.tfvars"
