name: Terraform AWS Deployment

on:
push:
branches:
- main
pull_request:
branches:
- main

permissions:
contents: read

jobs:
terraform:
name: Terraform
runs-on: ubuntu-latest

env:
AWS_REGION: ap-south-1
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

steps:
- name: Checkout Repository
uses: actions/checkout@v3

- name: Setup Terraform
uses: hashicorp/setup-terraform@v2
with:
terraform_version: 1.9.5 # change if needed

- name: Terraform Init
run: terraform init

- name: Terraform Format Check
run: terraform fmt -check

- name: Terraform Validate
run: terraform validate

- name: Terraform Plan
run: terraform plan -input=false

# Uncomment below step if you want auto-apply on push to main
# - name: Terraform Apply
# if: github.ref == 'refs/heads/main' && github.event_name == 'push'
# run: terraform apply -auto-approve -input=false
