name: Terraform AWS Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
  run: cd AWS && terraform init

- name: Terraform Validate
  run: cd AWS && terraform validate

- name: Terraform Plan
  run: cd AWS && terraform plan -out=tfplan

- name: Terraform Apply
  if: github.event_name == 'workflow_dispatch'
  run: cd AWS && terraform apply -auto-approve tfplan