name: Deploy Azure Blob Storage with Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7  # You can adjust this version as needed
      - name: Setup StateFile Storage
        run: |
          az login
          az group create --name devops-resource-group --location eastus
          az storage account create --name statefile --resource-group devops-resource-group --location eastus --sku Standard_LRS
          az storage container create --name tfstate --account-name statefile

      - name: Terraform Init
        run: |
          pwd
          cd Github_Copilot/Terraform_templates/AZ_Blob/
          pwd
          terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var="resource_group_name=your-rg-name" -var="location=East US"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="resource_group_name=your-rg-name" -var="location=East US"
