name: node_js Elasticbeanstack deployment

on:
  workflow_dispatch:

jobs:
  zip_app:
    name: Zip Inought Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and zip app
        run: |
          cd inought-service
          npm install
          zip -r inought-service.zip *

      - name: Upload zipped app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: inought-service-zip
          path: inought-service/inought-service.zip

  deploy_to_beanstalk:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest
    needs: zip_app

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download zipped app
        uses: actions/download-artifact@v4
        with:
          name: inought-service-zip
          path: inought-service

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply 
