stages:
  - zip
  - deploy

variables:
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY

zip_app:
  stage: zip
  image: node:18
  script:
    - cd inought-service
    - npm install
    - zip -r inought-service.zip *
  artifacts:
    paths:
      - inought-service/inought-service.zip

deploy_to_beanstalk:
  stage: deploy
  image: hashicorp/terraform:light
  script:
    - terraform -chdir=terraform init
    - terraform -chdir=terraform apply -auto-approve
  dependencies:
    - zip_app
  environment:
    name: production
